# Generated by Django 5.0.2 on 2025-09-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usersessionyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersessionyear',
            name='token',
        ),
    ]
