# Generated by Django 5.0.2 on 2025-11-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_sessionyear'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionyear',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
