# Generated by Django 5.0.2 on 2025-11-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_session_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_year',
        ),
    ]
