# Generated by Django 5.0.2 on 2025-11-05 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_session_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.sessionyear'),
        ),
    ]
