# Generated by Django 5.0.2 on 2025-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MillersEntry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='millersentrymodel',
            name='session_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
