# Generated by Django 5.0.2 on 2025-09-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reactivation', '0003_alter_reactivationmodels_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactivationmodels',
            name='session_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
