# Generated by Django 5.0.2 on 2025-10-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reactivation', '0005_reactivationextraletterhead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactivationextraletterhead',
            old_name='installation',
            new_name='reactivation',
        ),
    ]
