# Generated by Django 5.0.2 on 2025-09-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deactivation', '0003_alter_deactivationmodels_dealer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deactivationmodels',
            name='session_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
