# Generated by Django 5.0.2 on 2025-10-08 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deactivation', '0004_deactivationmodels_session_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivationExtraLetterHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deactivation/extra_letterheads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_letterheads', to='Deactivation.deactivationmodels')),
            ],
        ),
    ]
