# Generated by Django 5.0.2 on 2025-10-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deactivation', '0005_deactivationextraletterhead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deactivationextraletterhead',
            old_name='installation',
            new_name='deactivation',
        ),
    ]
