# Generated by Django 5.0.2 on 2025-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deactivation', '0006_rename_installation_deactivationextraletterhead_deactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deactivationmodels',
            name='otrMonth',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
