# Generated by Django 5.0.2 on 2024-11-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0002_alter_installatonmodels_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='installatonmodels',
            name='flag',
            field=models.CharField(default='old', max_length=15, null=True),
        ),
    ]
