# Generated by Django 5.0.2 on 2025-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0003_installatonmodels_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='installatonmodels',
            name='session_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
