# Generated by Django 5.0.2 on 2025-09-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0004_installatonmodels_session_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installatonmodels',
            name='session_year',
        ),
    ]
