# Generated by Django 5.0.2 on 2025-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0005_remove_installatonmodels_session_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='installatonmodels',
            name='session_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
