# Generated by Django 5.0.2 on 2025-09-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTREntry', '0002_alter_otrdata_installationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrdata',
            name='session_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
