# Generated by Django 5.0.2 on 2025-10-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTREntry', '0003_otrdata_session_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrdata',
            name='extendedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
