# Generated by Django 5.0.2 on 2025-11-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0002_dealersmodel_session_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealersmodel',
            name='Dealer_Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
